version: '3.9'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - react
      - django

    ports:
      - "80:80"

  react:
    build: frontend
    container_name: react-front
    command: npm run dev -- --host 0.0.0.0 --port 80
    depends_on:
      - django

  django:
    build: backend
    container_name: django-back
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - db-file:/var/www/app.backend/db

volumes:
  db-file:
