version: '3.9'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - react
      - django
      - adminer

    ports:
      - "80:80"

  react:
    build: frontend
    container_name: react-front
    restart: always
    command: npm run dev -- --host 0.0.0.0 --port 80
    depends_on:
      - django

  django:
    build: backend
    container_name: django-back
    restart: always
    command: python manage.py runserver 0.0.0.0:80
    environment:
      DJANGO_DB_ENGINE: django.db.backends.mysql
      DB_NAME: site
      DB_USER_NAME: root
      DB_USER_PASSWORD: 4813494d137e1631bba301d5acab6e7bb7aa74ce1185d456565ef51d737677b2
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 4813494d137e1631bba301d5acab6e7bb7aa74ce1185d456565ef51d737677b2
      MYSQL_DATABASE: site
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    links:
      - db:db
    depends_on:
      - db


volumes:
  db:
